<a href="https://colab.research.google.com/github/vedantrk/DAV-SEM6/blob/main/DAV_EXP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment 1:

Theory:

1.NumPy:- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


In [ ]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Array dimensions:",arr.ndim)
print("Element from )th row and 1st col:",arr[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array dimensions: 2
Element from )th row and 1st col: 3


2.Pandas:- Pandas is a powerful and versatile library that simplifies tasks of data manipulation in Python . Pandas is built on top of the NumPy library and is particularly well-suited for working with tabular data, such as spreadsheets or SQL tables. Its versatility and ease of use make it an essential tool for data analysts, scientists, and engineers working with structured data in Python.

In [ ]:
import pandas as pd

arr1=np.array(['h','e','l','l','o'])
ser=pd.Series(arr1)
print(ser)
arr2=np.array([['h','e','l','l','o'],['w','o','r','l','d'],['h','o','w'],['a','r','e'],['y','o','u']])
df=pd.DataFrame(arr2)
print(df.head())


0    h
1    e
2    l
3    l
4    o
dtype: object
                 0
0  [h, e, l, l, o]
1  [w, o, r, l, d]
2        [h, o, w]
3        [a, r, e]
4        [y, o, u]


<ipython-input-19-22833689226d>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2=np.array([['h','e','l','l','o'],['w','o','r','l','d'],['h','o','w'],['a','r','e'],['y','o','u']])


R

1.readr:- The goal of readr is to provide a fast and friendly way to read rectangular data from delimited files, such as comma-separated values (CSV) and tab-separated values (TSV). It is designed to parse many types of data found in the wild, while providing an informative problem report when parsing leads to unexpected results. If you are new to readr, the best place to start is the data import chapter in R for Data Science.

In [ ]:
library(readr)

# # Read data from a CSV file
my_data <- read_csv("/content/sample_data/mnist_test.csv")
subset_of_data <- head(my_data, 10)


New names:
• `0` -> `0...2`
• `0` -> `0...3`
• `0` -> `0...4`
• `0` -> `0...5`
• `0` -> `0...6`
• `0` -> `0...7`
• `0` -> `0...8`
• `0` -> `0...9`
• `0` -> `0...10`
• `0` -> `0...11`
• `0` -> `0...12`
• `0` -> `0...13`
• `0` -> `0...14`
• `0` -> `0...15`
• `0` -> `0...16`
• `0` -> `0...17`
• `0` -> `0...18`
• `0` -> `0...19`
• `0` -> `0...20`
• `0` -> `0...21`
• `0` -> `0...22`
• `0` -> `0...23`
• `0` -> `0...24`
• `0` -> `0...25`
• `0` -> `0...26`
• `0` -> `0...27`
• `0` -> `0...28`
• `0` -> `0...29`
• `0` -> `0...30`
• `0` -> `0...31`
• `0` -> `0...32`
• `0` -> `0...33`
• `0` -> `0...34`
• `0` -> `0...35`
• `0` -> `0...36`
• `0` -> `0...37`
• `0` -> `0...38`
• `0` -> `0...39`
• `0` -> `0...40`
• `0` -> `0...41`
• `0` -> `0...42`
• `0` -> `0...43`
• `0` -> `0...44`
• `0` -> `0...45`
• `0` -> `0...46`
• `0` -> `0...47`
• `0` -> `0...48`
• `0` -> `0...49`
• `0` -> `0...50`
• `0` -> `0...51`
• `0` -> `0...52`
• `0` -> `0...53`
• `0` -> `0...54`
• `0` -> `0...55`
• `0` -> `0...56`
• `0` -

2.stringr:-Have you ever found yourself working with character strings in R and struggling with complex string manipulation tasks? If yes, then the Stringr package might be the solution you need. As a part of the tidyverse ecosystem, the stringr package offers a range of functions for character string processing in R. The package is built on top of the stringi package, which provides efficient and dependable string processing functions.

In [ ]:
library(stringr)

my_string <- "Hello, World!"
str_length(my_string)
my_string <- "Hello, World!"
str_sub(my_string, start = 1, end = 5)


[1] 13

[1] "Hello"

Conclusion:

Identified the Data Analytics Libraries in Python and R.

Performed simple experiments with these libraries in Python and R.